// <auto-generated />
using System;
using Garden_Helper_Site.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garden_Helper_Site.Migrations
{
    [DbContext(typeof(Garden_Helper_SiteContext))]
    partial class Garden_Helper_SiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Garden_Helper_Site.Models.Plant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fertilizer_interval")
                        .HasColumnType("int");

                    b.Property<bool>("growing")
                        .HasColumnType("bit");

                    b.Property<int?>("maintenance_interval")
                        .HasColumnType("int");

                    b.Property<string>("maintenance_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("plant_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("time_till_fertilizer")
                        .HasColumnType("int");

                    b.Property<int?>("time_till_maintenance")
                        .HasColumnType("int");

                    b.Property<int>("time_till_water")
                        .HasColumnType("int");

                    b.Property<int>("water_interval")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Plant");
                });
#pragma warning restore 612, 618
        }
    }
}
