// <auto-generated />
using System;
using GardenHelper.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GardenHelper.Server.Migrations
{
    [DbContext(typeof(PlantDbContext))]
    partial class PlantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("GardenHelper.Server.Plant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FertilizerInterval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Growing")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaintenanceInterval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaintenanceType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlantedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeTillFertilizer")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeTillMaintenance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeTillWater")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaterInterval")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Garden");
                });
#pragma warning restore 612, 618
        }
    }
}
